### ISSUE TITLE
The application may be doing too much work on its main thread

### ISSUE THREAD

**Issue by AbdullahFaraedoonOmer** [kai-morich/SimpleUsbTerminal#30]
Hello friend how I can fix this, the UI become very slow when receive a lot of data and append it to TextView 
I/Choreographer: Skipped 31 frames!  The application may be doing too much work on its main thread.

**Comment by kai-morich** [comment]
instead of posting each data fragment to the message queue here: https://github.com/kai-morich/SimpleUsbTerminal/blob/ed4cf127908aee07f666fcb9073552b22ac54ad5/app/src/main/java/de/kai_morich/simple_usb_terminal/SerialService.java#L216
new data could be appended to the last message if it was not processed yet in the UI thread, with some additional synchronization logic

**Comment by AbdullahFaraedoonOmer** [comment]
Please can you help me I am new, for example give me example or solution

**Comment by kai-morich** [comment]
number of UI updates is reduced with: [7b88a50](https://github.com/kai-morich/SimpleUsbTerminal/commit/7b88a504ae47585e128e71f4c40ad95b9d351393)
